import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

const ASSET_EDITOR_URL = 'https://arcade.makecode.com/v4.1.4--asseteditor'
const ASSET_EDITOR_ORIGIN = 'https://arcade.makecode.com'

type AssetEditorEvent = {
  type: 'event'
  kind: 'ready' | 'done-clicked'
}

type AssetEditorResponse = {
  id?: number
  type?: 'open' | 'create' | 'save' | 'duplicate'
  files?: Record<string, string>
}

type AssetEditorMessage = AssetEditorEvent | AssetEditorResponse

type MakeCodeSongPreviewProps = {
  songHex: string
}

const buildAssetEditorFiles = (
  songHex: string,
): { assetId: string; files: Record<string, string> } => {
  const assetId = `preview_song_${songHex.slice(0, 16) || 'empty'}`

  const jres = {
    [assetId]: {
      id: assetId,
      mimeType: 'application/mkcd-song',
      data: songHex,
      displayName: 'preview song',
      namespace: 'songs',
    },
  }

  const pxtJson = {
    name: 'song-preview',
    dependencies: {
      device: '*',
    },
    files: ['main.ts', 'images.g.ts', 'images.g.jres'],
  }

  const mainTs = `const preview = assets.song\`${assetId}\`\nmusic.play(preview, music.PlaybackMode.InBackground)`
  const imagesGTs = `// Auto-generated by preview host\nnamespace assets {\n    //% fixedInstance jres blockIdentity=music.songs.songPicker\n    export const previewSong = song\`${assetId}\`\n}`

  return {
    assetId,
    files: {
      'pxt.json': JSON.stringify(pxtJson, null, 2),
      'main.ts': mainTs,
      'images.g.ts': imagesGTs,
      'images.g.jres': JSON.stringify(jres, null, 2),
    },
  }
}

export function MakeCodeSongPreview({ songHex }: MakeCodeSongPreviewProps) {
  const iframeRef = useRef<HTMLIFrameElement | null>(null)
  const requestIdRef = useRef(1)

  const [isReady, setIsReady] = useState(false)
  const [lastEvent, setLastEvent] = useState('Waiting for editor...')

  const { assetId, files } = useMemo(() => buildAssetEditorFiles(songHex), [songHex])

  const postMessage = useCallback((message: Record<string, unknown>) => {
    const targetWindow = iframeRef.current?.contentWindow
    if (!targetWindow) return
    targetWindow.postMessage(message, ASSET_EDITOR_ORIGIN)
  }, [])

  const openSongAsset = useCallback(() => {
    const id = requestIdRef.current++
    postMessage({
      id,
      type: 'open',
      assetId,
      assetType: 'song',
      files,
      response: true,
    })
    setLastEvent('Sent open request to asset editor')
  }, [assetId, files, postMessage])

  useEffect(() => {
    const onMessage = (event: MessageEvent<AssetEditorMessage>) => {
      if (event.origin !== ASSET_EDITOR_ORIGIN) return
      const data = event.data
      if (!data || typeof data !== 'object') return

      if ('kind' in data && data.type === 'event') {
        if (data.kind === 'ready') {
          setIsReady(true)
          setLastEvent('Asset editor ready')
          openSongAsset();
        } else if (data.kind === 'done-clicked') {
          setLastEvent('Asset editor emitted done-clicked event')
          const id = requestIdRef.current++
          postMessage({ id, type: 'save', files, response: true })
        }
        return
      }

      if ('type' in data && data.type === 'open') {
        setLastEvent('Song preview updated')
      } else if ('type' in data && data.type === 'save') {
        setLastEvent('Save response received from asset editor')
      }
    }

    window.addEventListener('message', onMessage)
    return () => window.removeEventListener('message', onMessage)
  }, [files, openSongAsset, postMessage])

  useEffect(() => {
    if (!isReady) return
    openSongAsset()
  }, [files, isReady, openSongAsset])

  return (
    <section className="panel preview-panel">
      <div className="panel-head">
        <h2>MakeCode Asset Editor Preview</h2>
        <p>{lastEvent}</p>
      </div>
      <iframe
        ref={iframeRef}
        title="MakeCode Asset Editor Preview"
        src={ASSET_EDITOR_URL}
        className="preview-iframe"
        sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
      />
    </section>
  )
}
